"""add_is_deleted_to_users

Revision ID: 03345926001b
Revises: e83f6fab37ac
Create Date: 2026-03-11 10:25:13.326199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03345926001b'
down_revision = 'e83f6fab37ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
