"""add_brought_and_extension_to_transactions

Revision ID: bcd58ab365e3
Revises: 03345926001b
Create Date: 2026-03-11 10:43:58.495724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd58ab365e3'
down_revision = '03345926001b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('brought_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('brought_id_card', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('brought_phone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('brought_phone')
        batch_op.drop_column('brought_id_card')
        batch_op.drop_column('brought_name')
        batch_op.drop_column('extension_count')

    # ### end Alembic commands ###
